### PR TITLE
Creality Sprite SE Extruder drive mount

### PR DESCRIPTION
**Pull request by Svennixx**
Confirmed that it works on my printer.
It's based on the LGX drive mount.
Added STEP and STL files.

### CODE REVIEW

**Comment by jon-harper** [comment]
Can you set the STL to print orientation?

**Comment by jon-harper** [comment]
P.S. For the BOM, it's 6x M3 x 6mm screws to mount the extruder?

**Comment by Svennixx** [comment]
Correct.
________________________________

**Comment by Svennixx** [comment]
Changed STL Orientation

**Comment by jon-harper** [comment]
Noice.

**Pull request merged**
